# Generated by Django 5.1.2 on 2024-11-12 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("validations", "0002_validationcore_error_message"),
    ]

    operations = [
        migrations.CreateModel(
            name="CounterAPIValidation",
            fields=[
                (
                    "validation_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="validations.validation",
                    ),
                ),
                (
                    "credentials",
                    models.JSONField(
                        help_text="Credentials for the SUSHI service used for the validation"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("validations.validation",),
        ),
    ]
