# Generated by Django 5.1.2 on 2024-11-12 12:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("validations", "0002_validationcore_error_message"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="validation",
            name="api_key",
        ),
        migrations.AddField(
            model_name="validation",
            name="api_key_prefix",
            field=models.CharField(blank=True, max_length=8),
        ),
    ]
