# Generated by Django 5.1.2 on 2024-11-13 11:08

from django.db import migrations, models


def copy_api_key_prefix_from_validation_to_validationcore(apps, schema_editor):
    Validation = apps.get_model("validations", "Validation")
    for validation in Validation.objects.all():
        validation.core.api_key_prefix = validation.api_key_prefix
        validation.core.save()


def copy_api_key_prefix_from_validationcore_to_validation(apps, schema_editor):
    Validation = apps.get_model("validations", "Validation")
    for validation in Validation.objects.all():
        validation.api_key_prefix = validation.core.api_key_prefix
        validation.save()


class Migration(migrations.Migration):
    dependencies = [
        ("validations", "0003_remove_validation_api_key_validation_api_key_prefix"),
    ]

    operations = [
        migrations.AddField(
            model_name="validationcore",
            name="api_key_prefix",
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.RunPython(
            copy_api_key_prefix_from_validation_to_validationcore,
            copy_api_key_prefix_from_validationcore_to_validation,
        ),
        migrations.RemoveField(
            model_name="validation",
            name="api_key_prefix",
        ),
    ]
