# Generated by Django 5.1.2 on 2024-11-15 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("validations", "0004_remove_validation_api_key_prefix_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CounterAPIValidation",
            fields=[
                (
                    "validation_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="validations.validation",
                    ),
                ),
                (
                    "credentials",
                    models.JSONField(
                        default=dict,
                        help_text="Credentials for the SUSHI service used for the validation",
                    ),
                ),
                ("url", models.URLField(help_text="URL of the SUSHI service")),
                ("api_endpoint", models.CharField(default="reports", max_length=64)),
                (
                    "requested_cop_version",
                    models.CharField(
                        blank=True,
                        help_text="COUNTER CoP version requested from the server",
                        max_length=16,
                    ),
                ),
                (
                    "requested_report_code",
                    models.CharField(
                        blank=True, help_text="Report code requested from the server", max_length=16
                    ),
                ),
                (
                    "requested_extra_attributes",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Extra attributes for the SUSHI request, e.g. report filters",
                    ),
                ),
                ("requested_begin_date", models.DateField()),
                ("requested_end_date", models.DateField()),
            ],
            options={
                "abstract": False,
            },
            bases=("validations.validation",),
        ),
    ]
