# Generated by Django 5.1.2 on 2024-11-21 15:57

import django.db.models.deletion
import uuid6
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("validations", "0005_counterapivalidation"),
    ]

    operations = [
        migrations.CreateModel(
            name="ValidationMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid6.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "number",
                    models.PositiveIntegerField(
                        default=0, help_text="Order of the message inside the validation results"
                    ),
                ),
                (
                    "severity",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, ""),
                            (10, "Passed"),
                            (20, "Notice"),
                            (30, "Warning"),
                            (40, "Error"),
                            (50, "Critical error"),
                            (60, "Fatal error"),
                        ]
                    ),
                ),
                ("code", models.CharField(blank=True, max_length=16)),
                ("location", models.TextField(blank=True)),
                ("message", models.TextField()),
                ("summary", models.TextField()),
                ("hint", models.TextField(blank=True)),
                ("data", models.TextField(blank=True)),
                (
                    "validation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="validations.validation",
                    ),
                ),
            ],
            options={
                "ordering": ["validation", "number", "pk"],
                "unique_together": {("validation", "number")},
            },
        ),
    ]
