# Generated by Django 5.1.2 on 2024-11-25 16:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("validations", "0006_validationmessage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="counterapivalidation",
            name="requested_begin_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="counterapivalidation",
            name="requested_end_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
