# Generated by Django 5.1.2 on 2024-12-03 08:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("validations", "0008_alter_validationcore_validation_result_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="validationcore",
            name="expiration_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
