# Generated by Django 5.1.2 on 2024-12-05 14:14

from django.db import migrations, models


def copy_api_endpoint_to_core(apps, schema_editor):
    CounterAPIValidation = apps.get_model("validations", "CounterAPIValidation")
    for counter_api_validation in CounterAPIValidation.objects.all():
        counter_api_validation.core.api_endpoint = counter_api_validation.api_endpoint
        counter_api_validation.core.save()


def copy_api_endpoint_from_core(apps, schema_editor):
    CounterAPIValidation = apps.get_model("validations", "CounterAPIValidation")
    for counter_api_validation in CounterAPIValidation.objects.all():
        counter_api_validation.api_endpoint = counter_api_validation.core.api_endpoint
        counter_api_validation.save()


class Migration(migrations.Migration):
    dependencies = [
        ("validations", "0009_validationcore_expiration_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="validationcore",
            name="api_endpoint",
            field=models.CharField(default="/reports/[id]", max_length=64),
        ),
        migrations.RunPython(copy_api_endpoint_to_core, copy_api_endpoint_from_core),
        migrations.RemoveField(
            model_name="counterapivalidation",
            name="api_endpoint",
        ),
    ]
