# Generated by Django 5.1.2 on 2024-12-05 15:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("validations", "0010_remove_counterapivalidation_api_endpoint_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="validation",
            name="public_id",
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
