# Generated by Django 5.1.2 on 2024-12-06 12:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("validations", "0011_validation_public_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="validationcore",
            name="platform",
        ),
        migrations.RemoveField(
            model_name="validationcore",
            name="platform_name",
        ),
    ]
