# Generated by Django 5.1.2 on 2024-12-17 07:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("validations", "0012_remove_validationcore_platform_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="validation",
            name="public_id",
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
    ]
