# Generated by Django 5.1.4 on 2024-12-19 15:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("validations", "0013_alter_validation_public_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="validationcore",
            name="api_endpoint",
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
