# Generated by Django 5.1.4 on 2024-12-20 11:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def copy_user_from_validation_to_validationcore(apps, schema_editor):
    Validation = apps.get_model("validations", "Validation")
    for validation in Validation.objects.all():
        validation.core.user = validation.user
        validation.core.save()


def copy_user_from_validationcore_to_validation(apps, schema_editor):
    Validation = apps.get_model("validations", "Validation")
    for validation in Validation.objects.all():
        validation.user = validation.core.user
        validation.save()


class Migration(migrations.Migration):
    dependencies = [
        ("validations", "0014_alter_validationcore_api_endpoint"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="validationcore",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RunPython(
            copy_user_from_validation_to_validationcore, copy_user_from_validationcore_to_validation
        ),
        migrations.RemoveField(
            model_name="validation",
            name="user",
        ),
    ]
