# Generated by Django 5.1.6 on 2025-02-14 09:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("validations", "0015_validationcore_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="counterapivalidation",
            name="use_short_dates",
            field=models.BooleanField(
                default=False,
                help_text="Use short dates (YYYY-MM instead of YYYY-MM-DD) for the request",
            ),
        ),
    ]
