# Generated by Django 5.1.6 on 2025-03-25 15:56

from django.db import migrations, models

# migrate all validations where there is an empty credentials dict to None


def migrate_credentials(apps, schema_editor):
    CounterAPIValidation = apps.get_model("validations", "CounterAPIValidation")
    CounterAPIValidation.objects.filter(credentials={}).update(credentials=None)


def reverse_migrate_credentials(apps, schema_editor):
    CounterAPIValidation = apps.get_model("validations", "CounterAPIValidation")
    CounterAPIValidation.objects.filter(credentials=None).update(credentials={})


class Migration(migrations.Migration):
    dependencies = [
        ("validations", "0016_counterapivalidation_use_short_dates"),
    ]

    operations = [
        migrations.AlterField(
            model_name="counterapivalidation",
            name="credentials",
            field=models.JSONField(
                default=dict,
                help_text="Credentials for the SUSHI service used for the validation",
                null=True,
            ),
        ),
        migrations.RunPython(migrate_credentials, reverse_migrate_credentials),
    ]
