# Generated by Django 5.2.8 on 2026-01-06 09:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("validations", "0017_alter_counterapivalidation_credentials"),
    ]

    operations = [
        migrations.AlterField(
            model_name="validationcore",
            name="report_code",
            field=models.CharField(
                blank=True,
                help_text="Code of the report as reported by the validation module",
                max_length=64,
            ),
        ),
    ]
