# Generated by Django 5.2.2 on 2025-07-03 07:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_user_is_validator_admin"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="receive_operator_emails",
            field=models.BooleanField(
                default=True,
                help_text="Whether this user should receive operator emails. Only relevant for admins.",
            ),
        ),
    ]
