export type CoP = "5" | "5.1"

export enum ReportCode {
  TR = "TR",
  TR_J1 = "TR_J1",
  TR_J2 = "TR_J2",
  TR_J3 = "TR_J3",
  TR_J4 = "TR_J4",
  TR_B1 = "TR_B1",
  TR_B2 = "TR_B2",
  TR_B3 = "TR_B3",
  PR = "PR",
  PR_P1 = "PR_P1",
  IR = "IR",
  IR_A1 = "IR_A1",
  IR_M1 = "IR_M1",
  DR = "DR",
  DR_D1 = "DR_D1",
  DR_D2 = "DR_D2",
}

export const reportDefinitions: {
  cop: CoP
  code: ReportCode
  name: string
  attributes: string[]
  metrics?: string[]
}[] = [
  // cop 5, title report
  {
    cop: "5",
    code: ReportCode.TR,
    name: "Title Master Report",
    attributes: ["Access_Method", "Access_Type", "Data_Type", "Section_Type", "YOP"],
    metrics: [
      "Total_Item_Investigations",
      "Total_Item_Requests",
      "Unique_Item_Investigations",
      "Unique_Item_Requests",
      "Unique_Title_Investigations",
      "Unique_Title_Requests",
      "Limit_Exceeded",
      "No_License",
    ],
  },
  {
    cop: "5",
    code: ReportCode.TR_B1,
    name: "Book Requests (Excluding OA_Gold)",
    attributes: [],
  },
  {
    cop: "5",
    code: ReportCode.TR_B2,
    name: "Book Access Denied",
    attributes: [],
  },
  {
    cop: "5",
    code: ReportCode.TR_B3,
    name: "Book Usage by Access Type",
    attributes: [],
  },
  {
    cop: "5",
    code: ReportCode.TR_J1,
    name: "Journal Requests (Excluding OA_Gold)",
    attributes: [],
  },
  {
    cop: "5",
    code: ReportCode.TR_J2,
    name: "Journal Access Denied",
    attributes: [],
  },
  {
    cop: "5",
    code: ReportCode.TR_J3,
    name: "Journal Usage by Access Type",
    attributes: [],
  },
  {
    cop: "5",
    code: ReportCode.TR_J4,
    name: "Journal Requests by YOP (Excluding OA_Gold)",
    attributes: [],
  },
  // cop 5, database report
  {
    cop: "5",
    code: ReportCode.DR,
    name: "Database Master Report",
    attributes: ["Access_Method", "Data_Type"],
    metrics: [
      "Searches_Automated",
      "Searches_Federated",
      "Searches_Regular",
      "Total_Item_Investigations",
      "Total_Item_Requests",
      "Unique_Item_Investigations",
      "Unique_Item_Requests",
      "Unique_Title_Investigations",
      "Unique_Title_Requests",
      "Limit_Exceeded",
      "No_License",
    ],
  },
  {
    cop: "5",
    code: ReportCode.DR_D1,
    name: "Database Search and Item Usage",
    attributes: [],
  },
  {
    cop: "5",
    code: ReportCode.DR_D2,
    name: "Database Access Denied",
    attributes: [],
  },
  // cop 5, platform report
  {
    cop: "5",
    code: ReportCode.PR,
    name: "Platform Master Report",
    attributes: ["Access_Method", "Data_Type"],
    metrics: [
      "Searches_Platform",
      "Total_Item_Investigations",
      "Total_Item_Requests",
      "Unique_Item_Investigations",
      "Unique_Item_Requests",
      "Unique_Title_Investigations",
      "Unique_Title_Requests",
    ],
  },
  {
    cop: "5",
    code: ReportCode.PR_P1,
    name: "Platform Usage",
    attributes: [],
  },
  // cop 5, item report
  {
    cop: "5",
    code: ReportCode.IR,
    name: "Item Master Report",
    attributes: [
      "Access_Method",
      "Access_Type",
      "Article_Version",
      "Authors",
      "Component_Authors",
      "Component_Data_Type",
      "Component_DOI",
      "Component_ISBN",
      "Component_Online_ISSN",
      "Component_Print_ISSN",
      "Component_Proprietary_ID",
      "Component_Publication_Date",
      "Component_Title",
      "Component_URI",
      "Data_Type",
      "Parent_Article_Version",
      "Parent_Authors",
      "Parent_Data_Type",
      "Parent_DOI",
      "Parent_ISBN",
      "Parent_Online_ISSN",
      "Parent_Print_ISSN",
      "Parent_Proprietary_ID",
      "Parent_Publication_Date",
      "Parent_Title",
      "Parent_URI",
      "Publication_Date",
      "YOP",
    ],
    metrics: [
      "Total_Item_Investigations",
      "Total_Item_Requests",
      "Unique_Item_Investigations",
      "Unique_Item_Requests",
      "Limit_Exceeded",
      "No_License",
    ],
  },
  {
    cop: "5",
    code: ReportCode.IR_A1,
    name: "Journal Article Requests",
    attributes: [],
  },
  {
    cop: "5",
    code: ReportCode.IR_M1,
    name: "Multimedia Item Requests",
    attributes: [],
  },

  // -- COP 5.1 --
  // cop 5.1, title report
  {
    cop: "5.1",
    code: ReportCode.TR,
    name: "Title Report",
    attributes: ["Access_Method", "Access_Type", "YOP"],
    metrics: [
      "Total_Item_Investigations",
      "Total_Item_Requests",
      "Unique_Item_Investigations",
      "Unique_Item_Requests",
      "Unique_Title_Investigations",
      "Unique_Title_Requests",
      "Limit_Exceeded",
      "No_License",
    ],
  },
  {
    cop: "5.1",
    code: ReportCode.TR_B1,
    name: "Book Requests (Controlled)",
    attributes: [],
  },
  {
    cop: "5.1",
    code: ReportCode.TR_B2,
    name: "Book Access Denied",
    attributes: [],
  },
  {
    cop: "5.1",
    code: ReportCode.TR_B3,
    name: "Book Usage by Access Type",
    attributes: [],
  },
  {
    cop: "5.1",
    code: ReportCode.TR_J1,
    name: "Journal Requests (Controlled)",
    attributes: [],
  },
  {
    cop: "5.1",
    code: ReportCode.TR_J2,
    name: "Journal Access Denied",
    attributes: [],
  },
  {
    cop: "5.1",
    code: ReportCode.TR_J3,
    name: "Journal Usage by Access Type",
    attributes: [],
  },
  {
    cop: "5.1",
    code: ReportCode.TR_J4,
    name: "Journal Requests by YOP (Controlled)",
    attributes: [],
  },
  // cop 5.1, database report
  {
    cop: "5.1",
    code: ReportCode.DR,
    name: "Database Report",
    attributes: ["Access_Method"],
    metrics: [
      "Searches_Automated",
      "Searches_Federated",
      "Searches_Regular",
      "Total_Item_Investigations",
      "Total_Item_Requests",
      "Unique_Item_Investigations",
      "Unique_Item_Requests",
      "Unique_Title_Investigations",
      "Unique_Title_Requests",
      "Limit_Exceeded",
      "No_License",
    ],
  },
  {
    cop: "5.1",
    code: ReportCode.DR_D1,
    name: "Database Search and Item Usage",
    attributes: [],
  },
  {
    cop: "5.1",
    code: ReportCode.DR_D2,
    name: "Database Access Denied",
    attributes: [],
  },
  // cop 5.1, platform report
  {
    cop: "5.1",
    code: ReportCode.PR,
    name: "Platform Report",
    attributes: ["Access_Method"],
    metrics: [
      "Searches_Platform",
      "Total_Item_Investigations",
      "Total_Item_Requests",
      "Unique_Item_Investigations",
      "Unique_Item_Requests",
      "Unique_Title_Investigations",
      "Unique_Title_Requests",
    ],
  },
  {
    cop: "5.1",
    code: ReportCode.PR_P1,
    name: "Platform Usage",
    attributes: [],
  },
  // cop 5.1, item report
  {
    cop: "5.1",
    code: ReportCode.IR,
    name: "Item Report",
    attributes: [
      "Access_Method",
      "Access_Type",
      "Article_Version",
      "Authors",
      "Component_Authors",
      "Component_Data_Type",
      "Component_DOI",
      "Component_ISBN",
      "Component_Online_ISSN",
      "Component_Print_ISSN",
      "Component_Proprietary_ID",
      "Component_Publication_Date",
      "Component_Title",
      "Component_URI",
      "Parent_Article_Version",
      "Parent_Authors",
      "Parent_Data_Type",
      "Parent_DOI",
      "Parent_ISBN",
      "Parent_Online_ISSN",
      "Parent_Print_ISSN",
      "Parent_Proprietary_ID",
      "Parent_Publication_Date",
      "Parent_Title",
      "Parent_URI",
      "Publication_Date",
      "YOP",
    ],
    metrics: [
      "Total_Item_Investigations",
      "Total_Item_Requests",
      "Unique_Item_Investigations",
      "Unique_Item_Requests",
      "Limit_Exceeded",
      "No_License",
    ],
  },
  {
    cop: "5.1",
    code: ReportCode.IR_A1,
    name: "Journal Article Requests",
    attributes: [],
  },
  {
    cop: "5.1",
    code: ReportCode.IR_M1,
    name: "Multimedia Item Requests",
    attributes: [],
  },
]

export const attributeValues: { cop: CoP; attr: string; values?: string[] }[] = [
  // -- COP 5 --
  { cop: "5", attr: "Access_Method", values: ["Regular", "TDM"] },
  { cop: "5", attr: "Access_Type", values: ["Controlled", "OA_Gold", "Other_Free_To_Read"] },
  {
    cop: "5",
    attr: "Data_Type",
    values: [
      "Article",
      "Book",
      "Book_Segment",
      "Database",
      "Dataset",
      "Journal",
      "Multimedia",
      "Newspaper_or_Newsletter",
      "Other",
      "Platform",
      "Report",
      "Repository_Item",
      "Thesis_or_Dissertation",
      "Unspecified",
    ],
  },
  {
    cop: "5",
    attr: "Section_Type",
    values: ["Article", "Book", "Chapter", "Other", "Section"],
  },
  {
    cop: "5",
    attr: "YOP",
  },
  // -- COP 5.1 --
  { cop: "5.1", attr: "Access_Method", values: ["Regular", "TDM"] },
  { cop: "5.1", attr: "Access_Type", values: ["Controlled", "Open", "Free_To_Read"] },
  {
    cop: "5.1",
    attr: "Data_Type",
    values: [
      "Article",
      "Audiovisual",
      "Book",
      "Book_Segment",
      "Conference",
      "Conference_Item",
      "Database_Aggregated",
      "Database_AI",
      "Database_Full",
      "Database_Full_Item",
      "Dataset",
      "Image",
      "Interactive_Resource",
      "Journal",
      "Multimedia",
      "News_Item",
      "Newspaper_or_Newsletter",
      "Other",
      "Patent",
      "Platform",
      "Reference_Item",
      "Reference_Work",
      "Report",
      "Software",
      "Sound",
      "Standard",
      "Thesis_or_Dissertation",
      "Unspecified",
    ],
  },
  {
    cop: "5.1",
    attr: "YOP",
  },
]

export function getReportInfo(cop: CoP, code: ReportCode) {
  return reportDefinitions.find((r) => r.cop === cop && r.code === code)
}

export function possibleAttributeValues(cop: CoP, attr: string) {
  return attributeValues.find((r) => r.cop === cop && r.attr === attr)?.values
}
