/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ApiKeyCreate: typeof import('./components/ApiKeyCreate.vue')['default']
    ApiKeyRevoke: typeof import('./components/ApiKeyRevoke.vue')['default']
    ApiKeyTable: typeof import('./components/ApiKeyTable.vue')['default']
    BarChart: typeof import('./components/BarChart.vue')['default']
    ChangePassword: typeof import('./components/ChangePassword.vue')['default']
    DateTooltip: typeof import('./components/DateTooltip.vue')['default']
    DoughnutChart: typeof import('./components/DoughnutChart.vue')['default']
    FilePicker: typeof import('./components/FilePicker.vue')['default']
    IsoDateTime: typeof import('./components/IsoDateTime.vue')['default']
    LoginPage: typeof import('./components/LoginPage.vue')['default']
    MonthPicker: typeof import('./components/MonthPicker.vue')['default']
    MonthRangePicker: typeof import('./components/MonthRangePicker.vue')['default']
    MsgDialog: typeof import('./components/MsgDialog.vue')['default']
    NewCounterAPIValidation: typeof import('./components/NewCounterAPIValidation.vue')['default']
    NewFileValidation: typeof import('./components/NewFileValidation.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SeverityLevelChip: typeof import('./components/SeverityLevelChip.vue')['default']
    ShortenText: typeof import('./components/ShortenText.vue')['default']
    SimplePie: typeof import('./components/SimplePie.vue')['default']
    SplitStatsVisualization: typeof import('./components/SplitStatsVisualization.vue')['default']
    StatsCard: typeof import('./components/StatsCard.vue')['default']
    StatsChip: typeof import('./components/StatsChip.vue')['default']
    StatsPie: typeof import('./components/StatsPie.vue')['default']
    StatsTableSimple: typeof import('./components/StatsTableSimple.vue')['default']
    TextTooltip: typeof import('./components/TextTooltip.vue')['default']
    UserEditWidget: typeof import('./components/UserEditWidget.vue')['default']
    UserForm: typeof import('./components/UserForm.vue')['default']
    UserTable: typeof import('./components/UserTable.vue')['default']
    ValidationBasicInfo: typeof import('./components/ValidationBasicInfo.vue')['default']
    ValidationCoreTable: typeof import('./components/ValidationCoreTable.vue')['default']
    ValidationDetailWidget: typeof import('./components/ValidationDetailWidget.vue')['default']
    ValidationExtractedInfo: typeof import('./components/ValidationExtractedInfo.vue')['default']
    ValidationFilterSet: typeof import('./components/ValidationFilterSet.vue')['default']
    ValidationManagementWidget: typeof import('./components/ValidationManagementWidget.vue')['default']
    ValidationMessagesTable: typeof import('./components/ValidationMessagesTable.vue')['default']
    ValidationMessageStatsTable: typeof import('./components/ValidationMessageStatsTable.vue')['default']
    ValidationStatus: typeof import('./components/ValidationStatus.vue')['default']
    ValidationTable: typeof import('./components/ValidationTable.vue')['default']
  }
}
