/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ApiKeyCreate: typeof import('./components/ApiKeyCreate.vue')['default']
    ApiKeyRevoke: typeof import('./components/ApiKeyRevoke.vue')['default']
    ApiKeyTable: typeof import('./components/ApiKeyTable.vue')['default']
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    ChangePassword: typeof import('./components/ChangePassword.vue')['default']
    ChangePasswordForm: typeof import('./components/ChangePasswordForm.vue')['default']
    DateTooltip: typeof import('./components/DateTooltip.vue')['default']
    FilePicker: typeof import('./components/FilePicker.vue')['default']
    FileUpload: typeof import('./components/FileUpload.vue')['default']
    FileUploader: typeof import('./components/FileUploader.vue')['default']
    FileValidation: typeof import('./components/FileValidation.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    LoginPage: typeof import('./components/LoginPage.vue')['default']
    MsgDialog: typeof import('./components/MsgDialog.vue')['default']
    NewFileValidation: typeof import('./components/NewFileValidation.vue')['default']
    NewSushiValidation: typeof import('./components/NewSushiValidation.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TextAreaDialog: typeof import('./components/TextAreaDialog.vue')['default']
    TextTooltip: typeof import('./components/TextTooltip.vue')['default']
    UserForm: typeof import('./components/UserForm.vue')['default']
    ValidationBasicInfo: typeof import('./components/ValidationBasicInfo.vue')['default']
    ValidationMessagesTable: typeof import('./components/ValidationMessagesTable.vue')['default']
    ValidationResult: typeof import('./components/ValidationResultChip.vue')['default']
    ValidationResultChip: typeof import('./components/ValidationResultChip.vue')['default']
    ValidationStatus: typeof import('./components/ValidationStatus.vue')['default']
  }
}
