/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...path]': RouteRecordInfo<'/[...path]', '/:path(.*)', { path: ParamValue<true> }, { path: ParamValue<false> }>,
    '/history': RouteRecordInfo<'/history', '/history', Record<never, never>, Record<never, never>>,
    '/public/[public_id]': RouteRecordInfo<'/public/[public_id]', '/public/:public_id', { public_id: ParamValue<true> }, { public_id: ParamValue<false> }>,
    '/settings': RouteRecordInfo<'/settings', '/settings', Record<never, never>, Record<never, never>>,
    '/stats': RouteRecordInfo<'/stats', '/stats', Record<never, never>, Record<never, never>>,
    '/validation/[id]': RouteRecordInfo<'/validation/[id]', '/validation/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/validation/admin': RouteRecordInfo<'/validation/admin', '/validation/admin', Record<never, never>, Record<never, never>>,
    '/validation/api': RouteRecordInfo<'/validation/api', '/validation/api', Record<never, never>, Record<never, never>>,
    '/validation/file': RouteRecordInfo<'/validation/file', '/validation/file', Record<never, never>, Record<never, never>>,
  }
}
