# Generated by Django 5.1.1 on 2024-10-16 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Platform",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=400)),
                ("abbrev", models.CharField(blank=True, max_length=50)),
                ("content_provider_name", models.CharField(blank=True, max_length=400)),
                ("website", models.URLField(blank=True)),
                ("deprecated", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                ("counter_release", models.CharField(max_length=20)),
                ("report_id", models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name="ReportToPlatform",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "platform",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="counter.platform"
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="counter.report"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="platform",
            name="reports",
            field=models.ManyToManyField(
                related_name="platforms", through="counter.ReportToPlatform", to="counter.report"
            ),
        ),
        migrations.CreateModel(
            name="SushiService",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("counter_release", models.CharField(max_length=20)),
                ("url", models.URLField(blank=True)),
                (
                    "ip_address_authorization",
                    models.BooleanField(
                        blank=True, help_text="Access restricted based on IP address", null=True
                    ),
                ),
                (
                    "api_key_required",
                    models.BooleanField(blank=True, help_text="Is api key required", null=True),
                ),
                (
                    "platform_attr_required",
                    models.BooleanField(
                        blank=True, help_text="Is platform attr required", null=True
                    ),
                ),
                (
                    "requestor_id_required",
                    models.BooleanField(
                        blank=True, help_text="Is requestor_id required", null=True
                    ),
                ),
                ("deprecated", models.BooleanField(default=False)),
                (
                    "platform",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sushi_services",
                        to="counter.platform",
                    ),
                ),
            ],
        ),
    ]
