# Generated by Django 5.1.2 on 2024-12-03 13:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("counter", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="platform",
            options={"ordering": ["name", "abbrev"]},
        ),
    ]
